version: '3.8'
services:
  event-gateway:
    build: ./event-gateway
    ports:
      - "8080:8080"
    depends_on:
      - account-service

  account-service:
    build: ./account-service
    ports:
      - "8081:8081"
